import { DayType, ItineraryDayVariation } from './types';

export const ITINERARY_VARIATIONS: ItineraryDayVariation[] = [
  // ARRIVAL VARIATIONS
  {
    id: 'v-arr-sri-pure',
    title: 'Arrival in Srinagar',
    dayType: DayType.ARRIVAL,
    source: 'Srinagar Airport',
    destination: 'Srinagar',
    routeType: 'Local',
    experienceTags: ['Easy Start'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '45 mins',
    internalNotes: 'Basic arrival.',
    customerDescription: 'Welcome to the paradise on earth. Upon arrival at Srinagar airport, our representative will assist you to your hotel/houseboat. Spend the rest of the day at leisure, relaxing after your flight.',
    luxuryEnhancement: 'Private luxury transfer and personalized welcome hamper.'
  },
  {
    id: 'v-arr-sri-doodh',
    title: 'Arrival and Doodhpathri Excursion',
    dayType: DayType.ARRIVAL,
    source: 'Srinagar Airport',
    destination: 'Doodhpathri',
    routeType: 'Direct',
    experienceTags: ['Meadows', 'Nature'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '3 hours',
    internalNotes: 'Direct from airport to meadow.',
    customerDescription: 'Start your trip with a breath of fresh alpine air. From the airport, we take you directly to the "Valley of Milk"—Doodhpathri, known for its pristine beauty.',
    luxuryEnhancement: 'Private luxury SUV and a gourmet picnic lunch in the meadows.'
  },
  {
    id: 'v-arr-sri-leisure',
    title: 'Arrival and Leisure Day',
    dayType: DayType.ARRIVAL,
    source: 'Srinagar Airport',
    destination: 'Srinagar',
    routeType: 'Local',
    experienceTags: ['Relaxation'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: 'Local',
    internalNotes: 'No activities planned.',
    customerDescription: 'Arrive and unwind. A smooth transfer to your accommodation where you can relax and soak in the soothing atmosphere of the Kashmir valley.',
    luxuryEnhancement: 'Suite upgrade and a personal butler service.'
  },
  {
    id: 'v-arr-jam-gul',
    title: 'Arrival in Jammu – Transfer to Gulmarg',
    dayType: DayType.ARRIVAL,
    source: 'Jammu',
    destination: 'Gulmarg',
    routeType: 'Direct',
    experienceTags: ['Long Drive', 'Mountains'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '7-8 hours',
    internalNotes: 'Long mountain highway journey.',
    customerDescription: 'Arrive in Jammu and embark on an epic drive towards the high altitudes of Gulmarg. Experience the dramatic climb from the plains to the snow-capped peaks.',
    luxuryEnhancement: 'Executive SUV with specialized refreshments and comfort stops.'
  },
  {
    id: 'v-arr-jam-son',
    title: 'Arrival in Jammu – Transfer to Sonamarg',
    dayType: DayType.ARRIVAL,
    source: 'Jammu',
    destination: 'Sonamarg',
    routeType: 'Direct',
    experienceTags: ['Long Drive', 'Riverside'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '8-9 hours',
    internalNotes: 'Very long journey.',
    customerDescription: 'A grand journey from the Shivalik foothills in Jammu to the gateway of Ladakh—Sonamarg. A day of traveling through the heart of the Himalayas.',
    luxuryEnhancement: 'Premium heavy SUV with integrated entertainment and snacks.'
  },
  {
    id: 'v-arr-jam-kat',
    title: 'Arrival in Jammu – Transfer to Katra',
    dayType: DayType.ARRIVAL,
    source: 'Jammu',
    destination: 'Katra',
    routeType: 'Local',
    experienceTags: ['Spiritual'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '1.5 hours',
    internalNotes: 'Short transfer to base camp.',
    customerDescription: 'Arrive in Jammu and take a short, comfortable drive to Katra, the base camp for your spiritual journey to Mata Vaishno Devi.',
    luxuryEnhancement: 'Private luxury sedan and express check-in at your hotel.'
  },
  {
    id: 'v-arr-jam-kat-local',
    title: 'Jammu Arrival and Local Katra',
    dayType: DayType.ARRIVAL,
    source: 'Jammu',
    destination: 'Katra',
    routeType: 'Local',
    experienceTags: ['Local'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '2 hours',
    internalNotes: 'Arrival plus some local exploration.',
    customerDescription: 'After arriving in Jammu and transferring to Katra, spend your evening exploring the vibrant local market of the holy town.',
    luxuryEnhancement: 'Guided spiritual tour of local Katra temples.'
  },
  {
    id: 'v-arr-kat-pure',
    title: 'Arrival in Katra',
    dayType: DayType.ARRIVAL,
    source: 'Katra',
    destination: 'Katra',
    routeType: 'Local',
    experienceTags: ['Arrival'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: 'Local',
    internalNotes: 'Station/helipad arrival.',
    customerDescription: 'Welcome to Katra. Our team will meet you at the station or helipad and assist you with your transfer to the hotel.',
    luxuryEnhancement: 'Private luxury transfer and specialized welcome.'
  },
  {
    id: 'v-arr-kat-sri',
    title: 'Arrival in Katra – Transfer to Srinagar',
    dayType: DayType.ARRIVAL,
    source: 'Katra',
    destination: 'Srinagar',
    routeType: 'Direct',
    experienceTags: ['Long Drive'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '7-8 hours',
    internalNotes: 'Connecting Jammu region to Kashmir.',
    customerDescription: 'Begin your journey in the spiritual town of Katra and travel across the mountains to the summer capital of Srinagar.',
    luxuryEnhancement: 'Luxury SUV for highway comfort.'
  },
  {
    id: 'v-sri-loc-tulip',
    title: 'Local Srinagar with Tulip Garden',
    dayType: DayType.SIGHTSEEING,
    source: 'Srinagar',
    destination: 'Srinagar',
    routeType: 'Local',
    experienceTags: ['Gardens', 'Seasonal'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Spring'],
    travelTimeApprox: 'Local',
    internalNotes: 'Spring specific.',
    customerDescription: 'A day immersed in the colors of spring. Witness the breathtaking bloom of the Tulip Garden followed by a visit to the Mughal Gardens.',
    luxuryEnhancement: 'VIP access to garden entries and a private botanical guide.'
  },
  {
    id: 'v-arr-sri-loc',
    title: 'Arrival and Local Srinagar',
    dayType: DayType.ARRIVAL,
    source: 'Srinagar Airport',
    destination: 'Srinagar',
    routeType: 'Local',
    experienceTags: ['Cultural', 'Lakeside'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: ['Shikara Ride', 'Wazwan Dinner'],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '45 mins',
    internalNotes: 'Standard arrival flow with local sightseeing.',
    customerDescription: 'Welcome to the summer capital of Jammu & Kashmir. Upon arrival at Srinagar Airport, our representative will greet you and assist with your transfer. Embark on a serene journey through the city, visiting the famous Mughal Gardens—Nishat and Shalimar. As the sun sets, check into your stay and soak in the alpine landscapes surrounding the valley.',
    luxuryEnhancement: 'Arrive in style with a private luxury transfer. Enjoy a curated Hi-Tea upon arrival overlooking the Zabarwan range and an evening private Shikara ride with live Kashmiri music.'
  },
  {
    id: 'v-arr-sri-tulip',
    title: 'Arrival and Local Srinagar with Tulip Garden',
    dayType: DayType.ARRIVAL,
    source: 'Srinagar Airport',
    destination: 'Srinagar',
    routeType: 'Local',
    experienceTags: ['Gardens', 'Seasonal'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: ['Tulip Garden Visit'],
    seasonalRelevance: ['Spring'],
    travelTimeApprox: '1 hour',
    internalNotes: 'Spring only arrival.',
    customerDescription: 'Experience the vibrant bloom of Asia\'s largest Tulip Garden. Upon arrival, you will be transferred to your stay with a beautiful detour through the rows of millions of tulips. The spring breeze and the colorful landscape provide a perfect start to your Kashmiri journey.',
    luxuryEnhancement: 'Private guided tour of the Tulip Garden before general hours. Exclusive botanical expert interaction and a floral-themed welcome drink.'
  },
  {
    id: 'v-arr-sri-pah',
    title: 'Arrival and Transfer to Pahalgam',
    dayType: DayType.ARRIVAL,
    source: 'Srinagar Airport',
    destination: 'Pahalgam',
    routeType: 'Direct',
    experienceTags: ['Scenic Drive', 'Riverfront'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: ['Saffron Shopping'],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '3 hours',
    internalNotes: 'Direct airport to Pahalgam transfer. Good for avoiding Srinagar traffic.',
    customerDescription: 'Your alpine adventure begins at the airport, where we whisk you away towards the "Valley of Shepherds"—Pahalgam. The scenic journey takes you through rolling saffron fields and ancient apple orchards. The Lidder River will be your companion as you approach your mountain retreat for an evening of riverside leisure.',
    luxuryEnhancement: 'Private luxury sedan/SUV transfer. Enroute stop for an exclusive saffron picking experience (seasonal) followed by a riverside candlelight dinner at your premium resort.'
  },
  {
    id: 'v-arr-sri-gul',
    title: 'Arrival and Transfer to Gulmarg',
    dayType: DayType.ARRIVAL,
    source: 'Srinagar Airport',
    destination: 'Gulmarg',
    routeType: 'Direct',
    experienceTags: ['Mountains', 'Direct'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '2 hours',
    internalNotes: 'Direct airport to Gulmarg.',
    customerDescription: 'Welcome to Kashmir. Your journey begins with a direct ascent to the meadows of Gulmarg. Watch the landscape transition from city life to majestic pine forests.',
    luxuryEnhancement: 'Luxury 4x4 transfer with specialized mountain driver. Hot refreshments served onboard.'
  },
  {
    id: 'v-arr-sri-son',
    title: 'Arrival and Transfer to Sonamarg',
    dayType: DayType.ARRIVAL,
    source: 'Srinagar Airport',
    destination: 'Sonamarg',
    routeType: 'Direct',
    experienceTags: ['Scenic', 'Riverside'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '3 hours',
    internalNotes: 'Direct airport to Sonamarg.',
    customerDescription: 'Upon arrival, embark on a scenic drive along the Sindh River towards the "Meadow of Gold"—Sonamarg. Check into your riverside hotel for a peaceful evening.',
    luxuryEnhancement: 'Private luxury SUV. Riverside picnic break enroute with premium snacks.'
  },
  {
    id: 'v-arr-sri-gurez',
    title: 'Arrival and Transfer to Gurez',
    dayType: DayType.ARRIVAL,
    source: 'Srinagar Airport',
    destination: 'Gurez',
    routeType: 'Direct',
    experienceTags: ['Offbeat', 'Adventure'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: ['Razdan Pass Stop'],
    seasonalRelevance: ['Summer', 'Spring'],
    travelTimeApprox: '6-7 hours',
    internalNotes: 'Long journey, requires early arrival.',
    customerDescription: 'A true adventure begins. Travel deep into the Himalayas to the untouched Gurez Valley. Cross the Razdan Pass and witness the Dardic culture.',
    luxuryEnhancement: 'Premium heavy SUV for rough terrain. Dedicated travel coordinator for the journey.'
  },
  {
    id: 'v-arr-jam-pah',
    title: 'Arrival in Jammu – Transfer to Pahalgam',
    dayType: DayType.ARRIVAL,
    source: 'Jammu',
    destination: 'Pahalgam',
    routeType: 'Direct',
    experienceTags: ['Long Drive', 'Scenic'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '6-7 hours',
    internalNotes: 'NH44 route.',
    customerDescription: 'Arrive in Jammu and head straight towards the pine forests of Pahalgam. A long but beautiful drive through the Shivalik foothills.',
    luxuryEnhancement: 'Private luxury SUV with on-board refreshments and specialized driver.'
  },
  {
    id: 'v-sri-pah-day',
    title: 'Pahalgam Day Trip',
    dayType: DayType.EXCURSION,
    source: 'Srinagar',
    destination: 'Pahalgam',
    routeType: 'Via-Scenic',
    experienceTags: ['Riverside', 'Meadows'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: ['ABC Valley Tour'],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '3 hours',
    internalNotes: 'Day trip variant.',
    customerDescription: 'Experience the "Valley of Shepherds" in a day. Visit the Lidder River, explore local parks, and soak in the alpine atmosphere before returning to Srinagar.',
    luxuryEnhancement: 'Private luxury transfer with a riverside lunch reservation.'
  },
  {
    id: 'v-sri-tosa-day',
    title: 'Tosamaidan Day Trip',
    dayType: DayType.EXCURSION,
    source: 'Srinagar',
    destination: 'Tosamaidan',
    routeType: 'Offbeat',
    experienceTags: ['Meadows', 'Untouched'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring'],
    travelTimeApprox: '3 hours',
    internalNotes: 'Offbeat destination.',
    customerDescription: 'Explore the vast, rolling meadows of Tosamaidan. A hidden gem known for its historical significance and pristine natural beauty.',
    luxuryEnhancement: 'Guided eco-trekking experience with a professional naturalist.'
  },

  // SRINAGAR SIGHTSEEING
  {
    id: 'v-sri-aharbal-day',
    title: 'Aharbal Day Trip',
    dayType: DayType.EXCURSION,
    source: 'Srinagar',
    destination: 'Aharbal',
    routeType: 'Offbeat',
    experienceTags: ['Waterfall', 'Nature'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '3 hours',
    internalNotes: 'Offbeat waterfall excursion.',
    customerDescription: 'Discover the "Niagara Falls of Kashmir"—Aharbal. Visit the majestic waterfall on the Veshu River and explore the surrounding pine forests.',
    luxuryEnhancement: 'Private lakeside picnic and a guided nature hike.'
  },
  {
    id: 'v-tra-sri-doodh',
    title: 'Srinagar – Doodhpathri Transfer',
    dayType: DayType.TRANSFER,
    source: 'Srinagar',
    destination: 'Doodhpathri',
    routeType: 'Direct',
    experienceTags: ['Meadows'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '2.5 hours',
    internalNotes: 'Transfer to meadow region.',
    customerDescription: 'Leave the city behind as you travel to the rolling green meadows of Doodhpathri for an overnight stay in nature.',
    luxuryEnhancement: 'Luxury SUV transfer with specialized refreshments.'
  },
  {
    id: 'v-tra-sri-yus',
    title: 'Srinagar – Yusmarg Transfer',
    dayType: DayType.TRANSFER,
    source: 'Srinagar',
    destination: 'Yusmarg',
    routeType: 'Direct',
    experienceTags: ['Offbeat'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '2.5 hours',
    internalNotes: 'Transfer to Yusmarg.',
    customerDescription: 'A scenic drive taking you to the untouched beauty of Yusmarg, known for its pristine forests and peaceful atmosphere.',
    luxuryEnhancement: 'Private luxury transfer with a nature coordinator.'
  },
  {
    id: 'v-tra-sri-kat',
    title: 'Srinagar – Katra Transfer',
    dayType: DayType.TRANSFER,
    source: 'Srinagar',
    destination: 'Katra',
    routeType: 'Direct',
    experienceTags: ['Long Drive'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '7-8 hours',
    internalNotes: 'Highway transfer.',
    customerDescription: 'A long journey from the Kashmir valley back to the holy base camp of Katra in the Jammu region.',
    luxuryEnhancement: 'Executive SUV and a specialized lunch stop enroute.'
  },
  {
    id: 'v-tra-sri-jam',
    title: 'Srinagar – Jammu Transfer',
    dayType: DayType.TRANSFER,
    source: 'Srinagar',
    destination: 'Jammu',
    routeType: 'Direct',
    experienceTags: ['Long Drive'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '7-8 hours',
    internalNotes: 'Return transfer to Jammu.',
    customerDescription: 'Descend through the mountain tunnels as you travel from the heights of Srinagar back to the city of temples—Jammu.',
    luxuryEnhancement: 'Premium heavy SUV for highway comfort.'
  },
  {
    id: 'v-tra-sri-jam-night',
    title: 'Srinagar – Overnight Jammu Drop',
    dayType: DayType.TRANSFER,
    source: 'Srinagar',
    destination: 'Jammu',
    routeType: 'Direct',
    experienceTags: ['Long Drive'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '8 hours',
    internalNotes: 'Includes overnight stay coordination.',
    customerDescription: 'A long transfer from Srinagar to Jammu designed for an overnight rest before your onward journey the next day.',
    luxuryEnhancement: 'Premium SUV transfer and stay in a specialized heritage hotel in Jammu.'
  },
  {
    id: 'v-tra-pah-son',
    title: 'Pahalgam – Sonamarg Transfer',
    dayType: DayType.TRANSFER,
    source: 'Pahalgam',
    destination: 'Sonamarg',
    routeType: 'Direct',
    experienceTags: ['Mountains'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '5 hours',
    internalNotes: 'Cross valley transfer.',
    customerDescription: 'Travel from the "Valley of Shepherds" to the "Meadow of Gold," witnessing the diverse beauty of the Kashmiri landscape.',
    luxuryEnhancement: 'Executive SUV with gourmet hampers.'
  },
  {
    id: 'v-tra-pah-doodh',
    title: 'Pahalgam – Dhoodpathri Transfer',
    dayType: DayType.TRANSFER,
    source: 'Pahalgam',
    destination: 'Doodhpathri',
    routeType: 'Direct',
    experienceTags: ['Meadows'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '4 hours',
    internalNotes: 'Transfer to offbeat meadow.',
    customerDescription: 'Cross over to the pristine meadows of Doodhpathri from the bustling river valley of Pahalgam.',
    luxuryEnhancement: 'Premium SUV and integrated refreshments.'
  },
  {
    id: 'v-tra-pah-jam',
    title: 'Pahalgam – Jammu Transfer',
    dayType: DayType.TRANSFER,
    source: 'Pahalgam',
    destination: 'Jammu',
    routeType: 'Direct',
    experienceTags: ['Long Drive'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '6-7 hours',
    internalNotes: 'Direct highway transfer.',
    customerDescription: 'Bid farewell to the Lidder valley as you take the mountain highway back to Jammu.',
    luxuryEnhancement: 'Luxury SUV for the long mountain journey.'
  },
  {
    id: 'v-tra-pah-kat',
    title: 'Pahalgam – Katra Transfer',
    dayType: DayType.TRANSFER,
    source: 'Pahalgam',
    destination: 'Katra',
    routeType: 'Direct',
    experienceTags: ['Scenic'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '6-7 hours',
    internalNotes: 'Highway transfer to pilgrimage site.',
    customerDescription: 'Travel from the pine forests of Pahalgam to the holy town of Katra.',
    luxuryEnhancement: 'Specialized comfort SUV with highway driver.'
  },
  {
    id: 'v-gul-atv-skiing',
    title: 'Gulmarg ATV & Skiing Experience',
    dayType: DayType.SIGHTSEEING,
    source: 'Gulmarg',
    destination: 'Gulmarg',
    routeType: 'Local',
    experienceTags: ['Adventure'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Winter'],
    travelTimeApprox: 'Local',
    internalNotes: 'Action focused.',
    customerDescription: 'Get your adrenaline pumping with a specialized ATV ride across the Gulmarg meadows followed by an introductory skiing session.',
    luxuryEnhancement: 'Private instructor and high-end equipment rental.'
  },
  {
    id: 'v-tra-gul-son',
    title: 'Gulmarg – Sonamarg Transfer',
    dayType: DayType.TRANSFER,
    source: 'Gulmarg',
    destination: 'Sonamarg',
    routeType: 'Direct',
    experienceTags: ['Scenic'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '4-5 hours',
    internalNotes: 'Major peak-to-peak transfer.',
    customerDescription: 'Travel from the rolling meadows of Gulmarg to the rugged mountains of Sonamarg.',
    luxuryEnhancement: 'Luxury SUV with onboard refreshments.'
  },
  {
    id: 'v-tra-gul-sri',
    title: 'Gulmarg – Srinagar Transfer',
    dayType: DayType.TRANSFER,
    source: 'Gulmarg',
    destination: 'Srinagar',
    routeType: 'Direct',
    experienceTags: ['Scenic'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '2 hours',
    internalNotes: 'Return to city.',
    customerDescription: 'After your alpine stay, return to the summer capital with a scenic descent from the Gulmarg heights.',
    luxuryEnhancement: 'Private luxury transfer.'
  },
  {
    id: 'v-tra-gul-kat',
    title: 'Gulmarg – Katra Transfer',
    dayType: DayType.TRANSFER,
    source: 'Gulmarg',
    destination: 'Katra',
    routeType: 'Direct',
    experienceTags: ['Long Drive'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '7-8 hours',
    internalNotes: 'Long cross-region journey.',
    customerDescription: 'A long drive connecting the heights of Gulmarg to the spiritual hills of Katra.',
    luxuryEnhancement: 'Premium heavy SUV for highway comfort.'
  },
  {
    id: 'v-tra-gul-jam',
    title: 'Gulmarg – Jammu Transfer',
    dayType: DayType.TRANSFER,
    source: 'Gulmarg',
    destination: 'Jammu',
    routeType: 'Direct',
    experienceTags: ['Long Drive'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '7-8 hours',
    internalNotes: 'Return transfer to Jammu.',
    customerDescription: 'Travel from the snowy peaks of Gulmarg back to the city of temples—Jammu.',
    luxuryEnhancement: 'Executive SUV transfer.'
  },
  {
    id: 'v-tra-gul-doodh',
    title: 'Gulmarg – Dhoodpathri Transfer',
    dayType: DayType.TRANSFER,
    source: 'Gulmarg',
    destination: 'Doodhpathri',
    routeType: 'Direct',
    experienceTags: ['Offbeat'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '3 hours',
    internalNotes: 'Offbeat connection.',
    customerDescription: 'Cross from the world-famous Gulmarg to the hidden "Valley of Milk"—Doodhpathri.',
    luxuryEnhancement: 'Private SUV transfer.'
  },
  {
    id: 'v-tra-son-gul',
    title: 'Sonamarg – Gulmarg Transfer',
    dayType: DayType.TRANSFER,
    source: 'Sonamarg',
    destination: 'Gulmarg',
    routeType: 'Direct',
    experienceTags: ['Scenic'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '5 hours',
    internalNotes: 'Major mountain transfer.',
    customerDescription: 'Travel from the rugged "Meadow of Gold" to the manicured meadows of Gulmarg.',
    luxuryEnhancement: 'Luxury SUV transfer.'
  },
  {
    id: 'v-tra-son-pah',
    title: 'Sonamarg – Pahalgam Transfer',
    dayType: DayType.TRANSFER,
    source: 'Sonamarg',
    destination: 'Pahalgam',
    routeType: 'Direct',
    experienceTags: ['Mountains'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '5-6 hours',
    internalNotes: 'Major peak-to-valley transfer.',
    customerDescription: 'Journey from the high-altitude Sonamarg peaks to the river-fed valleys of Pahalgam.',
    luxuryEnhancement: 'Executive SUV with gourmet snacks.'
  },
  {
    id: 'v-tra-son-doodh',
    title: 'Sonamarg – Dhoodpathri Transfer',
    dayType: DayType.TRANSFER,
    source: 'Sonamarg',
    destination: 'Doodhpathri',
    routeType: 'Direct',
    experienceTags: ['Offbeat'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '5 hours',
    internalNotes: 'Transfer to offbeat meadow.',
    customerDescription: 'Travel from the golden meadows of Sonamarg to the milky streams of Doodhpathri.',
    luxuryEnhancement: 'Private SUV transfer.'
  },
  {
    id: 'v-tra-son-kat',
    title: 'Sonamarg – Katra Transfer',
    dayType: DayType.TRANSFER,
    source: 'Sonamarg',
    destination: 'Katra',
    routeType: 'Direct',
    experienceTags: ['Long Drive'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '8-9 hours',
    internalNotes: 'Very long highway journey.',
    customerDescription: 'An epic cross-region journey from the high Himalayas to the pilgrimage base in Katra.',
    luxuryEnhancement: 'Premium heavy SUV with specialized comfort setup.'
  },
  {
    id: 'v-tra-son-jam',
    title: 'Sonamarg – Jammu Transfer',
    dayType: DayType.TRANSFER,
    source: 'Sonamarg',
    destination: 'Jammu',
    routeType: 'Direct',
    experienceTags: ['Long Drive'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '8-9 hours',
    internalNotes: 'Very long return journey.',
    customerDescription: 'Travel from the peaks of Sonamarg back to the city of temples—Jammu.',
    luxuryEnhancement: 'Executive SUV transfer.'
  },
  {
    id: 'v-tra-doodh-sri',
    title: 'Doodhpathri – Srinagar Transfer',
    dayType: DayType.TRANSFER,
    source: 'Doodhpathri',
    destination: 'Srinagar',
    routeType: 'Direct',
    experienceTags: ['Scenic'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '2.5 hours',
    internalNotes: 'Return from offbeat.',
    customerDescription: 'Return to the city lights after a peaceful soul-searching experience in the meadows of Doodhpathri.',
    luxuryEnhancement: 'Private luxury transfer.'
  },
  {
    id: 'v-tra-doodh-gul',
    title: 'Doodhpathri – Gulmarg Transfer',
    dayType: DayType.TRANSFER,
    source: 'Doodhpathri',
    destination: 'Gulmarg',
    routeType: 'Direct',
    experienceTags: ['Offbeat'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '3 hours',
    internalNotes: 'Connecting offbeat to peak.',
    customerDescription: 'Travel from the hidden Doodhpathri meadows to the world-famous alpine haven of Gulmarg.',
    luxuryEnhancement: 'Private SUV transfer.'
  },
  {
    id: 'v-tra-doodh-pah',
    title: 'Doodhpathri – Pahalgam Transfer',
    dayType: DayType.TRANSFER,
    source: 'Doodhpathri',
    destination: 'Pahalgam',
    routeType: 'Direct',
    experienceTags: ['Offbeat'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '4 hours',
    internalNotes: 'Connecting two beautiful meadow regions.',
    customerDescription: 'Journey from the "Valley of Milk" to the "Valley of Shepherds."',
    luxuryEnhancement: 'Private luxury SUV.'
  },
  {
    id: 'v-tra-doodh-son',
    title: 'Doodhpathri – Sonamarg Transfer',
    dayType: DayType.TRANSFER,
    source: 'Doodhpathri',
    destination: 'Sonamarg',
    routeType: 'Direct',
    experienceTags: ['Offbeat'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '5 hours',
    internalNotes: 'Cross-valley transfer.',
    customerDescription: 'Travel from the hidden Doodhpathri meadows to the rugged mountain scenery of Sonamarg.',
    luxuryEnhancement: 'Executive SUV transfer.'
  },
  {
    id: 'v-yus-day',
    title: 'Yusmarg Day Trip',
    dayType: DayType.EXCURSION,
    source: 'Srinagar',
    destination: 'Yusmarg',
    routeType: 'Offbeat',
    experienceTags: ['Meadows', 'Peace'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '2.5 hours',
    internalNotes: 'Offbeat day trip.',
    customerDescription: 'Discover the untouched "Meadow of Jesus"—Yusmarg. A tranquil location perfect for slow walks and soul-searching nature immersion.',
    luxuryEnhancement: 'Private guided nature talk and specialized picnic setup.'
  },
  {
    id: 'v-tra-yus-sri',
    title: 'Yusmarg – Srinagar Transfer',
    dayType: DayType.TRANSFER,
    source: 'Yusmarg',
    destination: 'Srinagar',
    routeType: 'Direct',
    experienceTags: ['Scenic'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '2 hours',
    internalNotes: 'Return to city.',
    customerDescription: 'Return to the summer capital after a day of serene exploration in the Yusmarg forests.',
    luxuryEnhancement: 'Private luxury transfer.'
  },
  {
    id: 'v-gurez-habba',
    title: 'Habba Khatoon Peak View',
    dayType: DayType.SIGHTSEEING,
    source: 'Gurez',
    destination: 'Gurez',
    routeType: 'Local',
    experienceTags: ['Views', 'Heritage'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring'],
    travelTimeApprox: 'Local',
    internalNotes: 'Gurez local.',
    customerDescription: 'Witness the majestic pyramid-shaped Habba Khatoon peak, named after the legendary poetess of Kashmir. Explore the historical significance and the divine beauty of this Dardic landmark.',
    luxuryEnhancement: 'Private storytelling session about the legend of Habba Khatoon and a sunset viewing from a premium spot.'
  },
  {
    id: 'v-gurez-kishan',
    title: 'Kishanganga River Experience',
    dayType: DayType.SIGHTSEEING,
    source: 'Gurez',
    destination: 'Gurez',
    routeType: 'Local',
    experienceTags: ['Riverside'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring'],
    travelTimeApprox: 'Local',
    internalNotes: 'Riverside activities.',
    customerDescription: 'Experience the crystal-blue waters of the Kishanganga River as it flows through the Gurez valley. Perfect for slow walks, photography, and finding peace by the running water.',
    luxuryEnhancement: 'Private luxury riverside lounge setup and a guided heritage walk through the nearby villages.'
  },
  {
    id: 'v-kat-shivkhori',
    title: 'Shiv Khori Excursion',
    dayType: DayType.EXCURSION,
    source: 'Katra',
    destination: 'Shiv Khori',
    routeType: 'Scenic',
    experienceTags: ['Spiritual', 'Cave'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '3 hours',
    internalNotes: 'Cave shrine excursion.',
    customerDescription: 'Visit the holy cave of Shiv Khori, a natural wonder dedicated to Lord Shiva. Witness the naturally formed Shiva Lingam and the intricate rock formations within the cave.',
    luxuryEnhancement: 'VIP group assistance and private luxury SUV for the drive.'
  },
  {
    id: 'v-tra-jam-verinag',
    title: 'Jammu Transfer via Verinag',
    dayType: DayType.TRANSFER,
    source: 'Jammu',
    destination: 'Srinagar',
    routeType: 'Via-Scenic',
    experienceTags: ['Gardens', 'Heritage'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '8 hours',
    internalNotes: 'Detour for sightseeing.',
    customerDescription: 'A grand transfer from Jammu to Srinagar with a special detour to Verinag Garden—the source of the Jhelum river. A perfect introduction to the architectural legacy of the Mughals.',
    luxuryEnhancement: 'Private guided tour of Verinag and an exclusive lunch setup in the garden area.'
  },
  {
    id: 'v-drop-kat',
    title: 'Katra Drop',
    dayType: DayType.DROP,
    source: 'Katra',
    destination: 'Katra Station/Helipad',
    routeType: 'Local',
    experienceTags: [],
    stayType: 'None',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '20 mins',
    internalNotes: 'Final station/helipad drop.',
    customerDescription: 'We provide a seamless transfer for your departure from Katra, ensuring you reach the station or helipad comfortably for your onward journey.',
    luxuryEnhancement: 'Porter assistance and priority drop-off.'
  },
  {
    id: 'v-drop-jam-night',
    title: 'Overnight Jammu Drop',
    dayType: DayType.DROP,
    source: 'Jammu',
    destination: 'Jammu Airport/Station',
    routeType: 'Local',
    experienceTags: [],
    stayType: 'None',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '30 mins',
    internalNotes: 'Final drop after overnight stay.',
    customerDescription: 'Assistance for your final departure from Jammu. After your overnight rest, we ensure a timely transfer to the airport or station.',
    luxuryEnhancement: 'Premium executive transfer and specialized luggage assistance.'
  },
  {
    id: 'v-drop-gul',
    title: 'Departure from Gulmarg',
    dayType: DayType.DROP,
    source: 'Gulmarg',
    destination: 'Srinagar Airport',
    routeType: 'Direct',
    experienceTags: ['Mountains'],
    stayType: 'None',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '2 hours',
    internalNotes: 'Direct peak to airport drop.',
    customerDescription: 'A direct and scenic transfer from the Gulmarg heights to the Srinagar airport for your flight back home.',
    luxuryEnhancement: 'Executive 4x4 transfer with specialized comfort amenities.'
  },
  {
    id: 'v-drop-pah',
    title: 'Departure from Pahalgam',
    dayType: DayType.DROP,
    source: 'Pahalgam',
    destination: 'Srinagar Airport',
    routeType: 'Direct',
    experienceTags: ['River Drive'],
    stayType: 'None',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '3 hours',
    internalNotes: 'Direct valley to airport drop.',
    customerDescription: 'Embark on your final drive from the Lidder valley to the airport, carrying the peace and beauty of the mountains with you.',
    luxuryEnhancement: 'Premium SUV transfer with specialized travel gifts.'
  },
  {
    id: 'v-drop-son',
    title: 'Departure from Sonamarg',
    dayType: DayType.DROP,
    source: 'Sonamarg',
    destination: 'Srinagar Airport',
    routeType: 'Direct',
    experienceTags: ['Highlands'],
    stayType: 'None',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '3 hours',
    internalNotes: 'Direct peak to airport drop.',
    customerDescription: 'Final transfer from the golden meadows to the Srinagar airport through the scenic Sindh valley highway.',
    luxuryEnhancement: 'Executive SUV transfer with integrated refreshments.'
  },
  {
    id: 'v-sri-loc-heritage',
    title: 'Srinagar Heritage & Old City',
    dayType: DayType.SIGHTSEEING,
    source: 'Srinagar',
    destination: 'Srinagar',
    routeType: 'Local',
    experienceTags: ['Heritage', 'Culture'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: ['Old City Walk', 'Spice Market Visit'],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: 'Local',
    internalNotes: 'Focus on history and culture.',
    customerDescription: 'Walk through the historical corridors of Srinagar. Visit the magnificent Jamia Masjid with its unique wooden architecture, the Shah-e-Hamdan shrine, and explore the bustling streets of Zaina Kadal. Discover the authentic flavors and crafts of the valley in its ancient alleys.',
    luxuryEnhancement: 'Private heritage expert as your guide. Exclusive access to a traditional copperware workshop and a specialized Kashmiri Wazwan lunch in a heritage home.'
  },
  {
    id: 'v-sri-loc-gardens-alt',
    title: 'Mughal Splendor & Hilltop Views',
    dayType: DayType.SIGHTSEEING,
    source: 'Srinagar',
    destination: 'Srinagar',
    routeType: 'Local',
    experienceTags: ['Gardens', 'Views'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: ['Paragliding', 'Shankaracharya Temple'],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: 'Local',
    internalNotes: 'Gardens plus hilltop.',
    customerDescription: 'Ascend the Shankaracharya hill for breathtaking panoramic views of the entire valley. Later, descend into the lush greenery of Chashme Shahi and Pari Mahal. The terraced gardens and the cool mountain springs provide a serene backdrop for a day of peaceful exploration.',
    luxuryEnhancement: 'Private sunset coffee at a premium hilltop lookout. Chauffeur-driven luxury sedan for a smooth mountain ascent.'
  },
  {
    id: 'v-sri-leisure',
    title: 'Srinagar Relaxation & Shikara',
    dayType: DayType.LEISURE,
    source: 'Srinagar',
    destination: 'Srinagar',
    routeType: 'Local',
    experienceTags: ['Leisure', 'Lakeside'],
    stayType: 'Houseboat',
    transferType: 'None',
    recommendedAddOns: ['Shikara Ride'],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: 'Local',
    internalNotes: 'Focus on relaxation.',
    customerDescription: 'Today is dedicated to slow travel. Wake up to the gentle ripples of Dal Lake. Enjoy your morning kahwa on the deck of your houseboat. The afternoon is free for you to explore the local markets or simply take a long, winding Shikara ride through the floating vegetable markets and lotus gardens.',
    luxuryEnhancement: 'Private breakfast on a decorated Shikara in the middle of the lake. Evening live Sufi music performance on the houseboat deck.'
  },

  // PAHALGAM SIGHTSEEING
  {
    id: 'v-pah-abc',
    title: 'ABC Valley Tour (Pahalgam)',
    dayType: DayType.SIGHTSEEING,
    source: 'Pahalgam',
    destination: 'Pahalgam',
    routeType: 'Local',
    experienceTags: ['Nature', 'Meadows'],
    stayType: 'Hotel',
    transferType: 'Union',
    recommendedAddOns: ['Pony Ride'],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '4-5 hours',
    internalNotes: 'Requires Union Cab (Aru, Betaab, Chandanwari).',
    customerDescription: 'Explore the iconic Aru Valley, Betaab Valley, and Chandanwari. These hidden meadows offer some of the most serene surroundings in Kashmir. Walk through lush pine forests or simply relax by the crystal-clear streams.',
    luxuryEnhancement: 'Private picnic breakfast in a secluded corner of Aru Valley. Access to premium union cabs with specialized local guides.'
  },
  {
    id: 'v-pah-local',
    title: 'Pahalgam Local Exploration',
    dayType: DayType.SIGHTSEEING,
    source: 'Pahalgam',
    destination: 'Pahalgam',
    routeType: 'Local',
    experienceTags: ['Nature', 'Walking'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: ['Club Park Visit', 'Lidder Amusement Park'],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: 'Local',
    internalNotes: 'Covers local parks and river banks.',
    customerDescription: 'Deepen your connection with Pahalgam by exploring its local gems. Visit the lush Club Park, stroll along the banks of the Lidder River, and explore the quaint local market. The evening is perfect for a scenic walk through the pine groves nearby.',
    luxuryEnhancement: 'Guided nature walk followed by a curated Hi-Tea experience at a riverside café with mountain views.'
  },
  {
    id: 'v-pah-leisure',
    title: 'Pahalgam Leisure Day',
    dayType: DayType.LEISURE,
    source: 'Pahalgam',
    destination: 'Pahalgam',
    routeType: 'Local',
    experienceTags: ['Relaxation'],
    stayType: 'Hotel',
    transferType: 'None',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: 'Local',
    internalNotes: 'Free day in Pahalgam.',
    customerDescription: 'Spend a relaxing day in the lap of nature. Walk along the Lidder river, explore the local markets, or simply enjoy the mountain views from your hotel balcony.',
    luxuryEnhancement: 'Private riverside bonfire and a specialized Kashmiri Wazwan dinner.'
  },
  {
    id: 'v-pah-shop-walk',
    title: 'Pahalgam Shopping & Café Walk',
    dayType: DayType.SIGHTSEEING,
    source: 'Pahalgam',
    destination: 'Pahalgam',
    routeType: 'Local',
    experienceTags: ['Culture', 'Food'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: 'Local',
    internalNotes: 'Market and cafe focus.',
    customerDescription: 'Explore the charming market of Pahalgam. Visit artisanal shops for authentic shawls and woodcrafts, and enjoy the cozy atmosphere of local riverside cafés.',
    luxuryEnhancement: 'Personal shopper assistance for authentic Kashmiri crafts.'
  },
  {
    id: 'v-gul-leisure',
    title: 'Gulmarg Leisure Day',
    dayType: DayType.LEISURE,
    source: 'Gulmarg',
    destination: 'Gulmarg',
    routeType: 'Local',
    experienceTags: ['Relaxation'],
    stayType: 'Hotel',
    transferType: 'None',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: 'Local',
    internalNotes: 'Free day in Gulmarg.',
    customerDescription: 'Enjoy the alpine silence of Gulmarg. Take slow walks through the meadows or enjoy the view of the snow-capped peaks from the comfort of your luxury stay.',
    luxuryEnhancement: 'Private spa session and a premium high-altitude tea service.'
  },
  {
    id: 'v-son-leisure',
    title: 'Sonamarg Leisure Day',
    dayType: DayType.LEISURE,
    source: 'Sonamarg',
    destination: 'Sonamarg',
    routeType: 'Local',
    experienceTags: ['Relaxation'],
    stayType: 'Hotel',
    transferType: 'None',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: 'Local',
    internalNotes: 'Free day in Sonamarg.',
    customerDescription: 'A day to breathe in the fresh mountain air of Sonamarg. Relax by the Sindh river or take short walks through the wildflower meadows.',
    luxuryEnhancement: 'Private riverside deck access for a peaceful afternoon.'
  },
  {
    id: 'v-tra-gul-pah',
    title: 'Gulmarg to Pahalgam Transfer',
    dayType: DayType.TRANSFER,
    source: 'Gulmarg',
    destination: 'Pahalgam',
    routeType: 'Direct',
    experienceTags: ['Long Drive', 'Scenic'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '4-5 hours',
    internalNotes: 'Major mountain transfer.',
    customerDescription: 'A journey across the valley from the heights of Gulmarg to the pine forests of Pahalgam. Watch the landscape change as you traverse the heart of Kashmir.',
    luxuryEnhancement: 'Luxury SUV with a specialized travel snack hamper.'
  },
  {
    id: 'v-tra-pah-gul',
    title: 'Pahalgam to Gulmarg Transfer',
    dayType: DayType.TRANSFER,
    source: 'Pahalgam',
    destination: 'Gulmarg',
    routeType: 'Direct',
    experienceTags: ['Scenic'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '4-5 hours',
    internalNotes: 'Return major transfer.',
    customerDescription: 'Travel from the river-fed valley of Pahalgam to the high meadows of Gulmarg, crossing through scenic countryside and quaint villages.',
    luxuryEnhancement: 'Executive SUV transfer with integrated refreshments.'
  },

  // GULMARG
  {
    id: 'v-gul-gondola',
    title: 'Gulmarg and Gondola',
    dayType: DayType.SIGHTSEEING,
    source: 'Gulmarg',
    destination: 'Gulmarg',
    routeType: 'Local',
    experienceTags: ['Adventure', 'Snow'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: ['Skiing Lesson', 'ATV Ride'],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: 'Local',
    internalNotes: 'Must pre-book Gondola tickets.',
    customerDescription: 'Experience the heights of Gulmarg with a ride on one of the world\'s highest cable cars. As you ascend towards Apharwat Peak, witness the breathtaking panoramic view of the Himalayan ranges. Whether it\'s winter snow or summer meadows, Gulmarg never fails to enchant.',
    luxuryEnhancement: 'VIP Gondola boarding assistance. Private ski instructor/guide and an exclusive hilltop lunch experience.'
  },
  {
    id: 'v-gul-snow',
    title: 'Gulmarg Snow Activities',
    dayType: DayType.SIGHTSEEING,
    source: 'Gulmarg',
    destination: 'Gulmarg',
    routeType: 'Local',
    experienceTags: ['Snow', 'Fun'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: ['Sledge Ride', 'Snowmobile'],
    seasonalRelevance: ['Winter'],
    travelTimeApprox: 'Local',
    internalNotes: 'Winter specific.',
    customerDescription: 'Dive into the winter wonderland. Engage in thrilling sledge rides, snowshoeing, or try your hand at snowmobiling across the vast white expanses of Gulmarg. The crisp mountain air and the pristine snow create memories that last a lifetime.',
    luxuryEnhancement: 'Private snow-tent setup with heaters and hot hot beverages. Guided snow-photography session.'
  },

  // SONAMARG
  {
    id: 'v-son-thajiwas',
    title: 'Thajiwas Glacier Experience',
    dayType: DayType.EXCURSION,
    source: 'Sonamarg',
    destination: 'Sonamarg',
    routeType: 'Local',
    experienceTags: ['Glacier', 'Trekking'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: ['Sledge Ride', 'Trout Fishing'],
    seasonalRelevance: ['Summer', 'Spring'],
    travelTimeApprox: '3-4 hours',
    internalNotes: 'Mainly a summer activity.',
    customerDescription: 'Journey to the "Meadow of Gold"—Sonamarg. A short trek or pony ride takes you to the stunning Thajiwas Glacier, where snow remains even in the peak of summer. The rugged mountain beauty and alpine landscapes here are truly cinematic.',
    luxuryEnhancement: 'Private riverside luxury camp setup for lunch. Curated fishing trip or specialized glacier trekking guide.'
  },
  {
    id: 'v-son-zeropoint',
    title: 'Zojila Pass and Zero Point',
    dayType: DayType.EXCURSION,
    source: 'Sonamarg',
    destination: 'Sonamarg',
    routeType: 'Local',
    experienceTags: ['Mountain Pass', 'Snow'],
    stayType: 'Hotel',
    transferType: 'Union',
    recommendedAddOns: ['Snow Activities'],
    seasonalRelevance: ['Summer'],
    travelTimeApprox: '5-6 hours',
    internalNotes: 'Requires 4x4 vehicle to cross Zojila.',
    customerDescription: 'Embark on a thrilling drive to Zero Point via the legendary Zojila Pass. This high-altitude excursion offers a stark contrast to the lush valleys below, featuring dramatic mountain scenery and year-round snow activities in a rugged setting.',
    luxuryEnhancement: 'Private premium 4x4 vehicle with an experienced mountain driver. Packed gourmet lunch with panoramic views of the Zojila pass.'
  },

  // TRANSFER VARIATIONS
  {
    id: 'v-arr-jam-sri',
    title: 'Jammu Arrival & Srinagar Transfer',
    dayType: DayType.ARRIVAL,
    source: 'Jammu Airport',
    destination: 'Srinagar',
    routeType: 'Direct',
    experienceTags: ['Long Drive', 'Scenic'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: ['Verinag Visit'],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '6-7 hours',
    internalNotes: 'NH44 journey.',
    customerDescription: 'Welcome to Jammu, the "City of Temples." Upon arrival, embark on a long and scenic drive towards the Kashmir Valley. As you ascend through the Banihal Tunnel, watch the landscape transform into the lush green paradise of Srinagar. Check into your hotel for a peaceful evening.',
    luxuryEnhancement: 'Private luxury SUV with onboard refreshments and specialized chauffeur for the mountain highway.'
  },
  {
    id: 'v-arr-kat-darshan',
    title: 'Katra Arrival and Vaishno Devi Darshan',
    dayType: DayType.ARRIVAL,
    source: 'Katra',
    destination: 'Katra',
    routeType: 'Local',
    experienceTags: ['Spiritual', 'Trek'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: ['Battery Car Booking', 'Helicopter Ride'],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '6-8 hours (Darshan)',
    internalNotes: 'Trek to Bhawan.',
    customerDescription: 'Your spiritual journey begins at Katra. After arrival and a brief rest, proceed for the holy darshan of Mata Vaishno Devi. Whether you choose to trek, take a pony, or a helicopter, the path is filled with divine energy. Return to your base camp in Katra by night.',
    luxuryEnhancement: 'VIP Darshan assistance and private helicopter transfers. Premium suite in Katra for post-darshan relaxation.'
  },
  // SRINAGAR EXCURSIONS
  {
    id: 'v-sri-doodh-day',
    title: 'Doodhpathri Day Excursion',
    dayType: DayType.EXCURSION,
    source: 'Srinagar',
    destination: 'Doodhpathri',
    routeType: 'Via-Scenic',
    experienceTags: ['Meadows', 'Nature'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: ['Pony Ride'],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '2.5 hours',
    internalNotes: 'Day trip from Srinagar.',
    customerDescription: 'Discover the "Valley of Milk"—Doodhpathri. This hidden gem near Srinagar features rolling green meadows and a crystal-clear river. It\'s an ideal spot for a peaceful picnic and short walks through the alpine scenery, far from the usual tourist trails.',
    luxuryEnhancement: 'Private luxury picnic setup with a personal butler. Guided meadow walk and specialized photography session in the meadows.'
  },
  {
    id: 'v-sri-yus-day',
    title: 'Yusmarg Day Excursion',
    dayType: DayType.EXCURSION,
    source: 'Srinagar',
    destination: 'Yusmarg',
    routeType: 'Via-Scenic',
    experienceTags: ['Serenity', 'Meadows'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: ['Trek to Nilnag'],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '2.5 hours',
    internalNotes: 'Day trip from Srinagar.',
    customerDescription: 'Travel to Yusmarg, often called the "Meadow of Jesus." This serene location is perfect for those seeking untouched natural beauty. Hike to the Nilnag Lake (optional) or simply enjoy the majestic views of the Doodh Ganga river and surrounding mountains.',
    luxuryEnhancement: 'Guided spiritual trekking experience. Curated hi-tea by the river side with premium Kashmiri snacks.'
  },
  {
    id: 'v-sri-gul-day',
    title: 'Gulmarg Day Trip',
    dayType: DayType.EXCURSION,
    source: 'Srinagar',
    destination: 'Gulmarg',
    routeType: 'Via-Scenic',
    experienceTags: ['Adventure', 'Snow'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: ['Gondola Ride'],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '2 hours',
    internalNotes: 'Day trip variant of Gulmarg.',
    customerDescription: 'A perfect day trip to the alpine meadows of Gulmarg. Take the Gondola ride to Apharwat peak, enjoy the panoramic views, and explore the high-altitude golf course. Return to Srinagar by evening, carrying the memories of the peaks with you.',
    luxuryEnhancement: 'VIP Gondola access and a private lunch reservation at a premium hilltop restaurant.'
  },
  {
    id: 'v-sri-son-day',
    title: 'Sonamarg Day Trip',
    dayType: DayType.EXCURSION,
    source: 'Srinagar',
    destination: 'Sonamarg',
    routeType: 'Via-Scenic',
    experienceTags: ['Glaciers', 'Mountains'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: ['Thajiwas Pony Ride'],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '3 hours',
    internalNotes: 'Day trip variant of Sonamarg.',
    customerDescription: 'Visit the "Meadow of Gold," Sonamarg, as a day excursion from Srinagar. Explore the gateway to Ladakh, take a pony ride to the Thajiwas Glacier, and witness the rugged beauty of the Himalayan ranges before returning to the city for the night.',
    luxuryEnhancement: 'Private riverside luxury lounge access for a quick break and curated travel gifts.'
  },
  {
    id: 'v-doodh-leisure',
    title: 'Doodhpathri Leisure Day',
    dayType: DayType.LEISURE,
    source: 'Doodhpathri',
    destination: 'Doodhpathri',
    routeType: 'Local',
    experienceTags: ['Riverside'],
    stayType: 'Hotel',
    transferType: 'None',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: 'Local',
    internalNotes: 'Stay in Doodhpathri.',
    customerDescription: 'Experience the pristine "Valley of Milk" at your own pace. Relax by the Doodh Ganga river and listen to the sounds of nature.',
    luxuryEnhancement: 'Private gourmet picnic set up by the river.'
  },
  {
    id: 'v-yus-picnic',
    title: 'Yusmarg Picnic Day',
    dayType: DayType.SIGHTSEEING,
    source: 'Yusmarg',
    destination: 'Yusmarg',
    routeType: 'Local',
    experienceTags: ['Meadows', 'Nature'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: 'Local',
    internalNotes: 'Focus on nature and picnic.',
    customerDescription: 'Spend a soulful day at Yusmarg. Known as the "Meadow of Jesus," this location offers unmatched peace and lush green landscapes perfect for a nature retreat.',
    luxuryEnhancement: 'Guided spiritual walk and a premium hamper of local delicacies.'
  },
  {
    id: 'v-gurez-leisure',
    title: 'Gurez Leisure Day',
    dayType: DayType.LEISURE,
    source: 'Gurez',
    destination: 'Gurez',
    routeType: 'Local',
    experienceTags: ['Offbeat', 'Peace'],
    stayType: 'Hotel',
    transferType: 'None',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring'],
    travelTimeApprox: 'Local',
    internalNotes: 'Slow stay in Gurez.',
    customerDescription: 'Immerse yourself in the Dardic culture of Gurez. A day to wake up to the view of Habba Khatoon peak and explore the village life at your own pace.',
    luxuryEnhancement: 'Evening interaction with local Dardic storytellers over a traditional bonfire.'
  },
  {
    id: 'v-gurez-valley',
    title: 'Gurez Valley Exploration',
    dayType: DayType.SIGHTSEEING,
    source: 'Gurez',
    destination: 'Gurez',
    routeType: 'Local',
    experienceTags: ['Adventure', 'Culture'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: ['Kishanganga River Visit'],
    seasonalRelevance: ['Summer', 'Spring'],
    travelTimeApprox: 'Local',
    internalNotes: 'Sightseeing in Gurez.',
    customerDescription: 'Discover the hidden corners of Gurez. Visit the iconic Habba Khatoon peak, the crystal-clear Kishanganga river, and the ancient villages that seem frozen in time.',
    luxuryEnhancement: 'Private guided photography tour of the Gurez landscapes.'
  },
  {
    id: 'v-tra-gurez-sri',
    title: 'Gurez to Srinagar Transfer',
    dayType: DayType.TRANSFER,
    source: 'Gurez',
    destination: 'Srinagar',
    routeType: 'Direct',
    experienceTags: ['Adventure'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring'],
    travelTimeApprox: '6-7 hours',
    internalNotes: 'Return from offbeat.',
    customerDescription: 'A long but rewarding journey back to the city, crossing the high-altitude Razdan Pass and witnessing the changing scenery of northern Kashmir.',
    luxuryEnhancement: 'Premium 4x4 transfer with specialized comfort amenities.'
  },
  {
    id: 'v-drop-sri-rly',
    title: 'Srinagar Railway Station Drop',
    dayType: DayType.DROP,
    source: 'Srinagar',
    destination: 'Srinagar Railway Station',
    routeType: 'Local',
    experienceTags: [],
    stayType: 'None',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '45 mins',
    internalNotes: 'Local station drop.',
    customerDescription: 'Assistance for your train departure from Srinagar. We ensure a smooth transfer to the station for your onward journey.',
    luxuryEnhancement: 'Porter assistance and express drop-off.'
  },
  {
    id: 'v-drop-jam-rly',
    title: 'Jammu Railway Station Drop',
    dayType: DayType.DROP,
    source: 'Jammu',
    destination: 'Jammu Tawi Railway Station',
    routeType: 'Local',
    experienceTags: [],
    stayType: 'None',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '30 mins',
    internalNotes: 'Jammu station drop.',
    customerDescription: 'Efficient transfer to Jammu Tawi station. We ensure you reach well in time for your train departure.',
    luxuryEnhancement: 'VIP lounge access at Jammu (if available) and premium porter assistance.'
  },
  {
    id: 'v-kat-leisure',
    title: 'Katra Leisure Day',
    dayType: DayType.LEISURE,
    source: 'Katra',
    destination: 'Katra',
    routeType: 'Local',
    experienceTags: ['Relaxation'],
    stayType: 'Hotel',
    transferType: 'None',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: 'Local',
    internalNotes: 'Rest day in Katra.',
    customerDescription: 'A day to rest and rejuvenate in Katra. Perfect for post-darshan relaxation or preparing for the spiritual journey ahead.',
    luxuryEnhancement: 'Private premium suite booking and specialized foot massage service.'
  },
  {
    id: 'v-kat-trek',
    title: 'Vaishno Devi Holy Trek',
    dayType: DayType.SIGHTSEEING,
    source: 'Katra',
    destination: 'Bhawan',
    routeType: 'Trek',
    experienceTags: ['Spiritual', 'Trek'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: ['Battery Car', 'Pony'],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '6-8 hours',
    internalNotes: 'The main pilgrimage trek.',
    customerDescription: 'Embark on the 12km holy trek to the Bhawan of Mata Vaishno Devi. Whether you walk, take a pony, or use the battery car, the path is filled with chants and spiritual energy.',
    luxuryEnhancement: 'VIP Darshan slip and priority access to helicopter services.'
  },
  {
    id: 'v-kat-sri-tra',
    title: 'Katra to Srinagar Transfer',
    dayType: DayType.TRANSFER,
    source: 'Katra',
    destination: 'Srinagar',
    routeType: 'Direct',
    experienceTags: ['Scenic', 'Long Drive'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: ['Kud Sweets Stop'],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '7-8 hours',
    internalNotes: 'Connecting Jammu region to Kashmir.',
    customerDescription: 'Travel from the holy town of Katra to the summer capital of Srinagar. Crossing the Banihal tunnel, witness the dramatic change in landscape and atmosphere.',
    luxuryEnhancement: 'Luxury SUV with specialized highway driver and gourmet snack hamper.'
  },
  {
    id: 'v-kat-pah-tra',
    title: 'Katra to Pahalgam Transfer',
    dayType: DayType.TRANSFER,
    source: 'Katra',
    destination: 'Pahalgam',
    routeType: 'Direct',
    experienceTags: ['Scenic'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '7-8 hours',
    internalNotes: 'Direct link to Pahalgam.',
    customerDescription: 'A long but scenic journey taking you from the foothills of Katra directly into the pine forests and river valleys of Pahalgam.',
    luxuryEnhancement: 'Premium heavy SUV for comfort over the mountain highways.'
  },
  {
    id: 'v-kat-jam-tra',
    title: 'Katra to Jammu Transfer',
    dayType: DayType.TRANSFER,
    source: 'Katra',
    destination: 'Jammu',
    routeType: 'Direct',
    experienceTags: ['Local'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '1.5 hours',
    internalNotes: 'Short transfer between city and base camp.',
    customerDescription: 'A quick and comfortable transfer from the pilgrimage base camp of Katra to the "City of Temples"—Jammu.',
    luxuryEnhancement: 'Private luxury sedan transfer with airport/station drop coordination.'
  },

  // TRANSFERS & STAYS FROM SCREENSHOTS
  {
    id: 'v-tra-pah-sri',
    title: 'Pahalgam to Srinagar Transfer',
    dayType: DayType.TRANSFER,
    source: 'Pahalgam',
    destination: 'Srinagar',
    routeType: 'Direct',
    experienceTags: ['Scenic'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: ['Apple Orchards'],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '3 hours',
    internalNotes: 'NH44 back to city.',
    customerDescription: 'Bid farewell to the Lidder valley as your scenic journey takes you back to Srinagar. Enroute, visit the saffron fields of Pampore and the ancient ruins of Awantipora. Check into your hotel or houseboat for a relaxing evening.',
    luxuryEnhancement: 'Private luxury SUV with a curated lunch stop at a premium heritage property enroute.'
  },
  {
    id: 'v-tra-sri-son',
    title: 'Srinagar to Sonamarg (Overnight)',
    dayType: DayType.TRANSFER,
    source: 'Srinagar',
    destination: 'Sonamarg',
    routeType: 'Direct',
    experienceTags: ['Mountains'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '3 hours',
    internalNotes: 'Overnight in Sonamarg.',
    customerDescription: 'Drive towards the "Meadow of Gold". Unlike a day trip, this overnight stay allows you to experience the serenity of Sonamarg after the day-crowds leave. Check into your riverside hotel and enjoy the alpine silence.',
    luxuryEnhancement: 'Stay in a premium riverside boutique property with a private evening bonfire and stargazing setup.'
  },
  {
    id: 'v-tra-son-sri',
    title: 'Sonamarg to Srinagar Transfer',
    dayType: DayType.TRANSFER,
    source: 'Sonamarg',
    destination: 'Srinagar',
    routeType: 'Direct',
    experienceTags: ['Scenic'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Spring', 'Autumn'],
    travelTimeApprox: '3 hours',
    internalNotes: 'Return transfer.',
    customerDescription: 'After a refreshing morning by the glacier, drive back to the summer capital. The descent offers a different perspective of the Sindh valley peaks.',
    luxuryEnhancement: 'Private luxury transfer with integrated refreshments.'
  },
  {
    id: 'v-tra-sri-pah-long',
    title: 'Srinagar to Pahalgam (Overnight)',
    dayType: DayType.TRANSFER,
    source: 'Srinagar',
    destination: 'Pahalgam',
    routeType: 'Direct',
    experienceTags: ['Riverside'],
    stayType: 'Hotel',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '3 hours',
    internalNotes: 'Transfer to Pahalgam for stay.',
    customerDescription: 'A scenic drive taking you to the "Valley of Shepherds". This transfer sets the mood for a multi-day stay in the most beautiful pine-forested region of Kashmir.',
    luxuryEnhancement: 'Executive SUV transfer with a specialized picnic hamper.'
  },
  {
    id: 'v-drop-jammu',
    title: 'Departure Transfer to Jammu',
    dayType: DayType.DROP,
    source: 'Srinagar',
    destination: 'Jammu',
    routeType: 'Direct',
    experienceTags: ['Mountain Highway'],
    stayType: 'None',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '7-8 hours',
    internalNotes: 'Long drop for Jammu Airport/Station.',
    customerDescription: 'As you depart from the paradise valley, we take you through the mountain highways towards Jammu. Re-cross the Banihal tunnel and descend into the foothills for your return journey home.',
    luxuryEnhancement: 'Premium heavy SUV for highway comfort with a dedicated travel coordinator assistance for station/airport drop.'
  },
  {
    id: 'v-drop-sri-air',
    title: 'Departure Transfer to Srinagar Airport',
    dayType: DayType.DROP,
    source: 'Srinagar',
    destination: 'Srinagar Airport',
    routeType: 'Direct',
    experienceTags: [],
    stayType: 'None',
    transferType: 'Private',
    recommendedAddOns: [],
    seasonalRelevance: ['Summer', 'Winter', 'Spring', 'Autumn'],
    travelTimeApprox: '1 hour',
    internalNotes: 'Transfer for departure.',
    customerDescription: 'Carry the serenity of the mountains back home. After a heart-warming stay, our representative will transfer you to Srinagar Airport for your onward journey, marking the end of your curated Kashmiri experience.',
    luxuryEnhancement: 'Express check-in assistance at the airport and a final souvenir gift bag from Travel Bliss.'
  }
];
